# Generated by Django 4.2.5 on 2023-11-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
