# Generated by Django 4.2.5 on 2023-11-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevApp', '0003_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
