# Generated by Django 4.2.5 on 2023-11-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevApp', '0004_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrtname', models.CharField(max_length=255)),
                ('ugr', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
            ],
        ),
    ]
