# Generated by Django 4.0.2 on 2023-11-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevApp', '0005_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='User_auth',
        ),
    ]
