# Generated by Django 4.0.2 on 2023-11-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevApp', '0006_delete_feedback_delete_user_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
